### ISSUE TITLE
[Question] Dual monitor support with basic driver on Pi 4?

### ISSUE THREAD

**Issue by stormenergy91** [raspberrypi/windows-drivers#34]
Hi, there is any way to enable dual screen support also if actualy there is no working driver video for a Pi 4? 

For helping in build the driver video there are some resource (or documentation) about the work to do and the actual stete of the driver?

**Comment by TheMindVirus** [comment]
Hi, the Basic Display Driver from the Windows Driver Samples can be customised to achieve dual monitor on the Raspberry Pi 4. 
I have a sample that works 50% of the time (unreliable due to the hardware refusing to provide the required data when it's required due to over-caching of I/O registers). Development files are available here: https://github.com/themindvirus/pi4bdd

**Comment by stormenergy91** [comment]
Thanks @TheMindVirus , I'll take a look!
