### ISSUE TITLE
WiFi driver 

### ISSUE THREAD

**Issue by Zaryob** [raspberrypi/windows-drivers#38]
Im using win11 preview using WOR. There is not wifi driver right now on the other hand Bluetooth working.

Is there any plan to get wifi for

**Comment by Zaryob** [comment]
???

**Comment by TheMindVirus** [comment]
Those that were working on it have either reported back that they burned themselves while accessing the registers on the WiFi module or they haven't reported back. It was supposed to use SDIO but might use SPI for all anyone currently knows about it.

The Pico W has since been released with a similar module and similar wiring "issues" that prevent the use of SDIO in favour of SPI for both Bluetooth and WiFi sides of the 2-headed BGA module.

On the Pi the UART for the Bluetooth is connected, on the Pico this isn't the case. Perhaps the expectation is to use the SPI line for the WiFi to also communicate with the Bluetooth Module. Once that works it may be able to relay the data to the Pi.

As for how this is all progressing, I imagine it to be very slow both in development and testing. Still waiting on official notes.
Commercial options are available that bridge WiFi to Ethernet, which might also be possible on a separate Pi with its own OS.

**Comment by Zaryob** [comment]
> Those that were working on it have either reported back that they burned themselves while accessing the registers on the WiFi module or they haven't reported back. It was supposed to use SDIO but might use SPI for all anyone currently knows about it.
> 
> The Pico W has since been released with a similar module and similar wiring "issues" that prevent the use of SDIO in favour of SPI for both Bluetooth and WiFi sides of the 2-headed BGA module.
> 
> On the Pi the UART for the Bluetooth is connected, on the Pico this isn't the case. Perhaps the expectation is to use the SPI line for the WiFi to also communicate with the Bluetooth Module. Once that works it may be able to relay the data to the Pi.
> 
> As for how this is all progressing, I imagine it to be very slow both in development and testing. Still waiting on official notes. Commercial options are available that bridge WiFi to Ethernet, which might also be possible on a separate Pi with its own OS.


I dont want to use PicoW as a wifi dongle or anything else. If I take a hardware, they need to share either source code or driver support. I'm very angry about all vendor about not supporting their boards. and Im so sorry.

**Comment by binarymaster** [comment]
The vendor (aka Broadcom) does not support Windows operating system on RPi.

Everything here is being developed and supported by volunteers. So either do it yourself, go find someone willing to do it, or just deal with it.

**Comment by Zaryob** [comment]
I think the person who produces a hardware should get the support of such a driver from the vendor. Although you say that everything in this repository is developed by volunteers, raspberry foundation should at least talk to the vendor and request it. And if this driver is not given, at least look under the issues of someone who asks about it, he has to write as a courtesy that there is such a situation.

I opened an issue 1 year ago. I asked a question about this on the forum. Didn't care. Now it is said that it does not have to support, either do it yourself or find someone to do it. I really feel annoyed by this reaction.

**Comment by binarymaster** [comment]
> I really feel annoyed by this reaction.

Note that I'm not affiliated with Broadcom or Raspberry Pi Foundation, this is just how I see this project. I'm also following the progress on it for a few years, and I believe my vision about it is correct. ¯\\_(ツ)_/¯
